# Generated by Django 5.2.8 on 2026-01-02 18:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Identificador URL')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('instructions', models.TextField(blank=True, verbose_name='Instrucciones de Juego')),
                ('category', models.CharField(choices=[('arcade', 'Arcade'), ('puzzle', 'Puzzle'), ('action', 'Acción'), ('strategy', 'Estrategia'), ('casual', 'Casual'), ('sports', 'Deportes')], default='casual', max_length=20, verbose_name='Categoría')),
                ('icon_url', models.URLField(blank=True, null=True, verbose_name='URL del Icono')),
                ('banner_url', models.URLField(blank=True, null=True, verbose_name='URL del Banner')),
                ('bundle_url', models.URLField(blank=True, null=True, verbose_name='URL del Bundle (para descarga)')),
                ('min_score', models.IntegerField(default=0, verbose_name='Puntaje Mínimo')),
                ('max_score', models.IntegerField(default=999999, verbose_name='Puntaje Máximo')),
                ('xp_per_play', models.PositiveIntegerField(default=10, verbose_name='XP por Partida')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('play_count', models.PositiveIntegerField(default=0, verbose_name='Veces Jugado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
                'ordering': ['-is_featured', '-play_count', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score_value', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Puntaje')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales específicos del juego (ej: personaje usado, tiempo, etc.)', verbose_name='Metadatos')),
                ('is_best', models.BooleanField(default=False, help_text='Indica si es el mejor puntaje del usuario en este juego', verbose_name='Es Mejor Puntaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Registro')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='games.game', verbose_name='Juego')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Puntaje',
                'verbose_name_plural': 'Puntajes',
                'ordering': ['-score_value', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='Hora de Inicio')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Fin')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Duración (segundos)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Sesión Completada')),
                ('device_info', models.JSONField(blank=True, default=dict, verbose_name='Información del Dispositivo')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games.game', verbose_name='Juego')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session', to='games.score', verbose_name='Puntaje Asociado')),
            ],
            options={
                'verbose_name': 'Sesión de Juego',
                'verbose_name_plural': 'Sesiones de Juego',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['game', '-score_value'], name='games_score_game_id_cfe8f1_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['user', 'game', '-score_value'], name='games_score_user_id_cac231_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['user', '-created_at'], name='games_score_user_id_325aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['user', '-start_time'], name='games_games_user_id_3183a0_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['game', '-start_time'], name='games_games_game_id_a171b9_idx'),
        ),
    ]
