# Generated by Django 5.2.8 on 2026-01-02 18:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('icon_url', models.URLField(blank=True, null=True, verbose_name='URL del Icono')),
                ('achievement_type', models.CharField(choices=[('games_played', 'Partidas Jugadas'), ('score_reached', 'Puntaje Alcanzado'), ('level_reached', 'Nivel Alcanzado'), ('friends_added', 'Amigos Añadidos'), ('consecutive_days', 'Días Consecutivos'), ('first_game', 'Primer Juego'), ('total_xp', 'XP Total'), ('time_played', 'Tiempo Jugado')], default='games_played', max_length=30, verbose_name='Tipo de Logro')),
                ('target_value', models.PositiveIntegerField(default=1, help_text='Valor que debe alcanzarse para desbloquear el logro', verbose_name='Valor Objetivo')),
                ('xp_reward', models.PositiveIntegerField(default=50, verbose_name='Recompensa XP')),
                ('rarity', models.CharField(choices=[('common', 'Común'), ('uncommon', 'Poco Común'), ('rare', 'Raro'), ('epic', 'Épico'), ('legendary', 'Legendario')], default='common', max_length=20, verbose_name='Rareza')),
                ('is_hidden', models.BooleanField(default=False, help_text='Los logros ocultos no se muestran hasta ser desbloqueados', verbose_name='Logro Oculto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('game', models.ForeignKey(blank=True, help_text='Dejar vacío para logros globales', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='games.game', verbose_name='Juego')),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'ordering': ['order', 'rarity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AchievementProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_value', models.PositiveIntegerField(default=0, verbose_name='Valor Actual')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_tracking', to='achievements.achievement', verbose_name='Logro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_progress', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Progreso de Logro',
                'verbose_name_plural': 'Progresos de Logros',
                'constraints': [models.UniqueConstraint(fields=('user', 'achievement'), name='unique_achievement_progress')],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Desbloqueo')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='Progreso Actual')),
                ('is_claimed', models.BooleanField(default=False, verbose_name='Recompensa Reclamada')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='achievements.achievement', verbose_name='Logro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Logro de Usuario',
                'verbose_name_plural': 'Logros de Usuario',
                'ordering': ['-unlocked_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'achievement'), name='unique_user_achievement')],
            },
        ),
    ]
